
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DOSPUNTOS = 44;
  public static final int RTRUE = 4;
  public static final int RWHILE = 11;
  public static final int RCONTINUE = 15;
  public static final int RNULL = 3;
  public static final int ENTERO = 48;
  public static final int LLDER = 21;
  public static final int PIZQ = 22;
  public static final int RDEFAULT = 18;
  public static final int PUNTOCOMA = 27;
  public static final int TERNARIO = 43;
  public static final int RFALSE = 5;
  public static final int CDER = 25;
  public static final int RELSE = 7;
  public static final int IDENTIFICADOR = 47;
  public static final int NOT = 42;
  public static final int AND = 40;
  public static final int RPRINT = 19;
  public static final int MAYORQUE = 37;
  public static final int IGUALQUE = 34;
  public static final int OR = 41;
  public static final int UMENOS = 50;
  public static final int RDO = 12;
  public static final int DECIMAL = 49;
  public static final int EOF = 0;
  public static final int ASIG = 26;
  public static final int MAYORIGUALQUE = 38;
  public static final int error = 1;
  public static final int COMA = 45;
  public static final int CADENA = 2;
  public static final int MODULO = 33;
  public static final int MENOS = 29;
  public static final int PDER = 23;
  public static final int MENORQUE = 36;
  public static final int POTENCIA = 32;
  public static final int RRETURN = 16;
  public static final int LLIZQ = 20;
  public static final int RCASE = 9;
  public static final int DISTINTOQUE = 35;
  public static final int CIZQ = 24;
  public static final int MENORIGUALQUE = 39;
  public static final int RIN = 14;
  public static final int RSWITCH = 8;
  public static final int ASGFUNCTION = 46;
  public static final int RFOR = 13;
  public static final int DIVISION = 31;
  public static final int RBREAK = 10;
  public static final int RIF = 6;
  public static final int RFUNCTION = 17;
  public static final int MULTIPLICACION = 30;
  public static final int MAS = 28;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "CADENA",
  "RNULL",
  "RTRUE",
  "RFALSE",
  "RIF",
  "RELSE",
  "RSWITCH",
  "RCASE",
  "RBREAK",
  "RWHILE",
  "RDO",
  "RFOR",
  "RIN",
  "RCONTINUE",
  "RRETURN",
  "RFUNCTION",
  "RDEFAULT",
  "RPRINT",
  "LLIZQ",
  "LLDER",
  "PIZQ",
  "PDER",
  "CIZQ",
  "CDER",
  "ASIG",
  "PUNTOCOMA",
  "MAS",
  "MENOS",
  "MULTIPLICACION",
  "DIVISION",
  "POTENCIA",
  "MODULO",
  "IGUALQUE",
  "DISTINTOQUE",
  "MENORQUE",
  "MAYORQUE",
  "MAYORIGUALQUE",
  "MENORIGUALQUE",
  "AND",
  "OR",
  "NOT",
  "TERNARIO",
  "DOSPUNTOS",
  "COMA",
  "ASGFUNCTION",
  "IDENTIFICADOR",
  "ENTERO",
  "DECIMAL",
  "UMENOS"
  };
}

