
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int RTRUE = 6;
  public static final int IDENTIFICADOR = 68;
  public static final int DIVISION = 52;
  public static final int RFALSE = 7;
  public static final int RARRAY = 36;
  public static final int RLENGTH = 24;
  public static final int MENORIGUALQUE = 60;
  public static final int POTENCIA = 53;
  public static final int RELSE = 9;
  public static final int RIN = 16;
  public static final int RNULL = 3;
  public static final int RIF = 8;
  public static final int RCONTINUE = 17;
  public static final int RFUNCTION = 19;
  public static final int RHIST = 40;
  public static final int RNCOL = 25;
  public static final int RWHILE = 13;
  public static final int NOT = 63;
  public static final int DISTINTOQUE = 56;
  public static final int MENORQUE = 57;
  public static final int RREMOVE = 28;
  public static final int PDER = 44;
  public static final int RLIST = 4;
  public static final int LLIZQ = 41;
  public static final int RC = 22;
  public static final int RTRUNK = 31;
  public static final int RBREAK = 12;
  public static final int RTYPEOF = 23;
  public static final int RPIE = 37;
  public static final int RCASE = 11;
  public static final int CIZQ = 45;
  public static final int COMA = 66;
  public static final int RMEAN = 33;
  public static final int RPRINT = 21;
  public static final int MAYORIGUALQUE = 59;
  public static final int ENTERO = 69;
  public static final int MODULO = 54;
  public static final int RMATRIX = 5;
  public static final int DECIMAL = 70;
  public static final int DOSPUNTOS = 65;
  public static final int ASGFUNCTION = 67;
  public static final int MENOS = 50;
  public static final int MAS = 49;
  public static final int EOF = 0;
  public static final int RBARPLOT = 38;
  public static final int RMODE = 35;
  public static final int RROUND = 32;
  public static final int RFOR = 15;
  public static final int RTOUPPERCASE = 30;
  public static final int RTOLOWERCASE = 29;
  public static final int RNROW = 26;
  public static final int IGUALQUE = 55;
  public static final int OR = 62;
  public static final int error = 1;
  public static final int PIZQ = 43;
  public static final int MAYORQUE = 58;
  public static final int UMENOS = 71;
  public static final int MULTIPLICACION = 51;
  public static final int PUNTOCOMA = 48;
  public static final int ASIG = 47;
  public static final int CADENA = 2;
  public static final int RSTRINGLENGTH = 27;
  public static final int RSWITCH = 10;
  public static final int TERNARIO = 64;
  public static final int LLDER = 42;
  public static final int RRETURN = 18;
  public static final int AND = 61;
  public static final int RMEDIAN = 34;
  public static final int RDO = 14;
  public static final int RPLOT = 39;
  public static final int CDER = 46;
  public static final int RDEFAULT = 20;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "CADENA",
  "RNULL",
  "RLIST",
  "RMATRIX",
  "RTRUE",
  "RFALSE",
  "RIF",
  "RELSE",
  "RSWITCH",
  "RCASE",
  "RBREAK",
  "RWHILE",
  "RDO",
  "RFOR",
  "RIN",
  "RCONTINUE",
  "RRETURN",
  "RFUNCTION",
  "RDEFAULT",
  "RPRINT",
  "RC",
  "RTYPEOF",
  "RLENGTH",
  "RNCOL",
  "RNROW",
  "RSTRINGLENGTH",
  "RREMOVE",
  "RTOLOWERCASE",
  "RTOUPPERCASE",
  "RTRUNK",
  "RROUND",
  "RMEAN",
  "RMEDIAN",
  "RMODE",
  "RARRAY",
  "RPIE",
  "RBARPLOT",
  "RPLOT",
  "RHIST",
  "LLIZQ",
  "LLDER",
  "PIZQ",
  "PDER",
  "CIZQ",
  "CDER",
  "ASIG",
  "PUNTOCOMA",
  "MAS",
  "MENOS",
  "MULTIPLICACION",
  "DIVISION",
  "POTENCIA",
  "MODULO",
  "IGUALQUE",
  "DISTINTOQUE",
  "MENORQUE",
  "MAYORQUE",
  "MAYORIGUALQUE",
  "MENORIGUALQUE",
  "AND",
  "OR",
  "NOT",
  "TERNARIO",
  "DOSPUNTOS",
  "COMA",
  "ASGFUNCTION",
  "IDENTIFICADOR",
  "ENTERO",
  "DECIMAL",
  "UMENOS"
  };
}

